[build]
  base = ""
  command = "npm run netlify-build"
  publish = "client/build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[[plugins]]
  package = "./netlify/build-plugins/setup-function"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express", "serverless-http", "cors", "multer"]

# Serve the React app on all routes not handled by functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Serve static documentation
[[redirects]]
  from = "/docs/*"
  to = "/docs/:splat"
  status = 200

# Serve the React app on all unhandled routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optimize asset caching
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 